# Copyright (c) 2024-2025 Accenture, All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{- $name := .Release.Name }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $name }}-nginx-conf
  labels:
    app.kubernetes.io/name: {{ $name }}
data:
  default.conf.template: |
    map $http_upgrade $connection_upgrade {
      default upgrade;
      ''      close;
    }

    server {
      listen 8080;

      location = /healthz {
        add_header Content-Type text/plain;
        return 200 'ok';
      }

      location / {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_set_header Authorization "Bearer ${DASHBOARD_TOKEN}";

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;

        proxy_pass http://{{ .Values.upstream.host }}:{{ .Values.upstream.port }};

        proxy_buffering off;
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  labels:
    app.kubernetes.io/name: {{ $name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ $name }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      automountServiceAccountToken: true
      volumes:
      - name: templates
        configMap:
          name: {{ $name }}-nginx-conf
      - name: conf
        emptyDir: {}
      initContainers:
      - name: render-config
        image: alpine:3.18
        command:
        - /bin/sh
        - -c
        - |
          apk add --no-cache gettext >/dev/null 2>&1 || true
          if [ -f /var/run/secrets/kubernetes.io/serviceaccount/token ]; then
            TOKEN="$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)"
          else
            TOKEN=""
          fi
          export DASHBOARD_TOKEN="${TOKEN}"
          envsubst '\${DASHBOARD_TOKEN}' < /templates/default.conf.template > /conf/default.conf
        volumeMounts:
        - name: templates
          mountPath: /templates
          readOnly: true
        - name: conf
          mountPath: /conf
      containers:
      - name: nginx
        image: nginx:1.23
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: conf
          mountPath: /etc/nginx/conf.d
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 5
          periodSeconds: 10
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 5
          periodSeconds: 20
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
spec:
  selector:
    app.kubernetes.io/name: {{ $name }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8080