# Copyright (c) 2026 Accenture, All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# registry internal url
{{- $registry_internal_url := printf "http://registry.%s.svc.cluster.local:%d" .Values.app.namespace (int .Values.registry.service.ports.api) }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}-mcpgw-server
  namespace: {{ .Values.app.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app.name }}-mcpgw-server
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}-mcpgw-server
    spec:
      containers:
        - name: mcpgw-server
          image: "mcpgateway/{{ .Values.mcpgwServer.image.repository }}:{{ .Values.mcpgwServer.image.tag }}"
          imagePullPolicy: {{ .Values.mcpgwServer.image.pullPolicy }}
          ports:
            - containerPort: 8003
          env:
            - name: PORT
              value: "8003"
            - name: REGISTRY_BASE_URL
              value: {{ $registry_internal_url | quote }}
            - name: REGISTRY_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mcp-gateway-registry-app-admin
                  key: username
            - name: REGISTRY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mcp-gateway-registry-app-admin
                  key: password
          volumeMounts:
            - name: servers
              mountPath: /app/registry/servers
            - name: models
              mountPath: /app/registry/models
            - name: scopes
              mountPath: /app/auth_server/scopes.yml
              subPath: scopes.yml
      volumes:
        - name: servers
          emptyDir: {}
        - name: models
          emptyDir: {}
        - name: scopes
          configMap:
            name: {{ .Values.app.name }}-user-scopes-config
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mcpgwServer.service.name }}
  namespace: {{ .Values.app.namespace }}
spec:
  selector:
    app: {{ .Values.app.name }}-mcpgw-server
  ports:
    - name: http
      port: {{ .Values.mcpgwServer.service.ports.api }}
      targetPort: 8003
  type: {{ .Values.mcpgwServer.service.type }}
